package main

import (
	"bufio"
	"encoding/csv"
	"fmt"
	"io"
	"log"
	"os"
	"regexp"
	"sort"
	"strconv"
)

type entry struct {
	step  float64
	short string
	long  string
}

func main() {
	f, _ := os.Open("normadresse.csv")
	reader := csv.NewReader(bufio.NewReader(f))
	entries := []entry{}
	for i := 0; ; i++ {
		line, err := reader.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
		if i == 0 { // skip first line
			continue
		}
		// there is an "option" row in the csv header
		// but there is no entry with a value at the time
		// I'm writing this script.
		if line[3] != "" {
			log.Fatal(fmt.Errorf("not implemented"))
		}
		step, err := strconv.ParseFloat(line[0], 64)
		if err != nil {
			log.Fatal(err)
		}
		long := line[1]
		short := line[2]
		short = regexp.MustCompile(`\\g<([0-9]+)>`).ReplaceAllString(short, "$${$1}")
		entries = append(entries, entry{
			step:  step,
			long:  long,
			short: short,
		})
	}

	// add missing rules (based on normaddress.py)
	entries = append(entries, entry{
		step:  10,
		long:  " (LE|LA|LES|AU|AUX|DE|DU|DES|D|ET|A|L|SUR|EN) ",
		short: " ",
	})
	entries = append(entries, entry{
		step:  12,
		long:  " (le|la|les|au|aux|de|du|des|d|et|a|l|sur) ",
		short: " ",
	})

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].step < entries[j].step
	})

	fmt.Println("// autogenerated file, please do not edit")
	fmt.Println("package normadresse")
	fmt.Println("var rules = []rule{")
	for _, entry := range entries {
		fmt.Printf("{%f, %q, %q},\n", entry.step, entry.short, entry.long)
	}
	fmt.Println("}")
}
